version: '3'

services:
   db:
      image: mysql:8.0.27
      container_name: mysql
      restart: always
      volumes:
         - /home/betocalestini/mysqldb:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=admin
         - TZ=America/Sao_Paulo
      ports:
         - 3307:3306
      networks:
         - rede1

networks:
   rede1:
      name: rede1
      driver: bridge
